### ISSUE TITLE
issue to install in linux using the yml file 

### ISSUE THREAD

**Issue by HuaizhenC** [fbcsptoolbox/fbcsp_code#1]
Hi, 
I use the code
conda env create --name fbcsp --file fbcsp.yml 
to install the package in linux, 
however, it indicated the following error, 

Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

ResolvePackageNotFound: 
  - libgfortran=3.0.1
  - libcxx=10.0.0
  - llvm-openmp=10.0.0

Any suggestions about why this happened will be very helpful! Thank u!!

**Comment by thetushar006** [comment]
Hi, thanks for reaching out! You probably faced the issue because the yml file included in the repo was made from a Windows environment. Please use this attached file instead, to create an environment to run this code on Linux. This new environment file has been created to enable cross-platform sharing of the environment. Please let us know if you still face any issues.
[environment.zip](https://github.com/fbcsptoolbox/fbcsp_code/files/8249794/environment.zip)

**Comment by fbcsptoolbox** [comment]
We are now closing this issue. In case the problem persists, please feel free to re-open it. Thanks!
